Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/test/FlaskAPP/application.py", line 44, in generateReport
    return dbaUMI.read_fromDB()
  File "/home/test/FlaskAPP/dbaccesslibUserMailInfo.py", line 36, in read_fromDB
    dall.update(newjson)
TypeError: 'NoneType' object is not iterable
{'userDeleted': True, 'otherdbref': DBRef('mydb.userInfo', ObjectId('5d15ecfd926fc4678bc9db99')), 'scan_date': datetime.datetime(2019, 7, 1, 14, 43, 12, 821000), 'end_date': datetime.datetime(2019, 7, 11, 14, 43, 12, 821000), 'code': '1234'}
127.0.0.1 - - [01/Jul/2019 15:16:05] "[1m[35mGET /generateReport HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/test/FlaskAPP/application.py", line 44, in generateReport
    return dbaUMI.read_fromDB()
  File "/home/test/FlaskAPP/dbaccesslibUserMailInfo.py", line 36, in read_fromDB
    dall.update(newjson)
TypeError: 'NoneType' object is not iterable
 * Detected change in '/home/test/FlaskAPP/dbaccesslibUserMailInfo.py', reloading
 * Restarting with stat
Obtained the client
 * Debugger is active!
 * Debugger PIN: 120-406-930
Obtained the client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dbaccesslibUserMailInfo' has no attribute 'clearDB'

KeyboardInterrupt

{'scan_date': datetime.datetime(2019, 7, 1, 14, 43, 12, 821000), 'code': '1234', 'otherdbref': DBRef('mydb.userInfo', ObjectId('5d15ecfd926fc4678bc9db99')), 'userDeleted': True, 'end_date': datetime.datetime(2019, 7, 11, 14, 43, 12, 821000)}
127.0.0.1 - - [01/Jul/2019 15:18:03] "[1m[35mGET /generateReport HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/test/FlaskAPP/application.py", line 44, in generateReport
    return dbaUMI.read_fromDB()
  File "/home/test/FlaskAPP/dbaccesslibUserMailInfo.py", line 36, in read_fromDB
    dall.update(newjson)
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [01/Jul/2019 15:19:39] "[37mGET /generateReport HTTP/1.1[0m" 200 -
127.0.0.1 - - [01/Jul/2019 15:19:44] "[37mGET /getConfig HTTP/1.1[0m" 200 -
127.0.0.1 - - [01/Jul/2019 15:19:53] "[37mPOST /addToUserMailInfo HTTP/1.1[0m" 200 -
{'code': '123545', 'scan_date': datetime.datetime(2019, 7, 1, 15, 19, 53, 844000), 'end_date': datetime.datetime(2019, 7, 11, 15, 19, 53, 844000), 'userDeleted': False, 'otherdbref': DBRef('mydb.userInfo', ObjectId('5d19d631926fc41b01ab280c'))}
{'scan_date': datetime.datetime(2019, 7, 1, 15, 19, 53, 844000), 'department': 'TTEC_SL', 'userDeleted': False, 'end_date': datetime.datetime(2019, 7, 11, 15, 19, 53, 844000), 'code': '123545', 'building': 'Essae', 'division': 'TTEC', 'name': 'Arvind Mohan'}
127.0.0.1 - - [01/Jul/2019 15:19:56] "[37mGET /generateReport HTTP/1.1[0m" 200 -
 * Detected change in '/home/test/FlaskAPP/dbaccesslibUserMailInfo.py', reloading
Obtained the client
 * Restarting with stat
Obtained the client
 * Debugger is active!
 * Debugger PIN: 120-406-930
Obtained the client
